export type PersonaStatus = 'active' | 'draft' | 'training' | 'paused' | 'archived';

export interface Persona {
  id: string;
  name: string;
  slug: string;
  description: string;
  subCategory: string;
  status: PersonaStatus;
  avatar: string;
  channels: string[];
  services: string[];
  knowledgeChunks: number;
  messagesTotal: number;
  lastActive: string;
  createdAt: string;
  voice: string;
  language: string;
  whatsappNumber?: string;
  isPublic?: boolean;
}

export const personas: Persona[] = [
  {
    id: 'persona-001',
    name: 'ZaraSkin Sales Agent',
    slug: 'zara-skin-sales',
    subCategory: 'D2C Skincare',
    description: 'D2C skincare AI agent — recommends products, answers ingredient questions, and guides customers to their perfect routine to drive conversions',
    status: 'active',
    avatar: 'ZS',
    channels: ['WhatsApp', 'Web Chat', 'API'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 9100,
    messagesTotal: 73600,
    lastActive: '2 min ago',
    createdAt: 'Jan 18, 2026',
    voice: 'Aria (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+91 98765 43210',
  },
  {
    id: 'persona-002',
    name: 'NutriBlend Store Bot',
    slug: 'nutriblend-store-bot',
    subCategory: 'D2C Nutrition',
    description: 'D2C nutrition brand agent — handles product discovery, subscription upsells, and pre-purchase Q&A for protein and supplement SKUs',
    status: 'active',
    avatar: 'NB',
    channels: ['Web Chat', 'API'],
    services: ['ElevenLabs'],
    knowledgeChunks: 12400,
    messagesTotal: 94100,
    lastActive: '8 min ago',
    createdAt: 'Nov 3, 2025',
    voice: 'Rachel (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-003',
    name: 'StyleHouse Fashion Bot',
    slug: 'stylehouse-fashion-bot',
    subCategory: 'D2C Fashion',
    description: 'D2C fashion brand agent — assists with size recommendations, outfit pairing, and order tracking across seasonal collections',
    status: 'active',
    avatar: 'SH',
    channels: ['WhatsApp', 'Web Chat'],
    services: ['Omnidimension'],
    knowledgeChunks: 8200,
    messagesTotal: 41800,
    lastActive: '1 hr ago',
    createdAt: 'Feb 5, 2026',
    voice: 'Maya (Omnidimension)',
    language: 'English, Hindi',
    whatsappNumber: '+91 98765 43211',
  },
  {
    id: 'persona-004',
    name: 'FitFuel Voice Agent',
    slug: 'fitfuel-voice-agent',
    subCategory: 'D2C Fitness Supplements',
    description: 'D2C fitness supplement brand — voice-enabled agent for product recommendations, workout pairing, and subscription management',
    status: 'active',
    avatar: 'FF',
    channels: ['Voice AI', 'API'],
    services: ['ElevenLabs', 'Tavus'],
    knowledgeChunks: 5240,
    messagesTotal: 28600,
    lastActive: '22 min ago',
    createdAt: 'Mar 1, 2026',
    voice: 'Kai (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-005',
    name: 'GlowUp Beauty Agent',
    slug: 'glowup-beauty-agent',
    subCategory: 'D2C Beauty',
    description: 'D2C beauty brand agent — engages shoppers 24/7, recommends bundles, answers shade-match questions, and promotes new launches',
    status: 'active',
    avatar: 'GB',
    channels: ['Web Chat', 'WhatsApp', 'API'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 7840,
    messagesTotal: 62300,
    lastActive: '5 min ago',
    createdAt: 'Mar 10, 2026',
    voice: 'Alex (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+1 (650) 555-0142',
  },
  {
    id: 'persona-006',
    name: 'TheoGear Product Concierge',
    slug: 'theogear-product-concierge',
    subCategory: 'D2C Everyday Carry',
    description: 'D2C everyday carry brand — helps customers choose the right bag, accessories, and workspace gear from the minimalist product catalog',
    status: 'active',
    avatar: 'TG',
    channels: ['Web Chat', 'API'],
    services: ['Heygen', 'Tavus'],
    knowledgeChunks: 4600,
    messagesTotal: 31500,
    lastActive: '3 hr ago',
    createdAt: 'Feb 20, 2026',
    voice: 'Adam (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-007',
    name: 'StreamGuide — Crime Drama',
    slug: 'streamguide-crime-drama',
    subCategory: 'OTT Content Discovery',
    description: 'OTT viewer engagement persona for crime drama series — character Q&A, episode recaps, and personalized content discovery',
    status: 'active',
    avatar: 'SG',
    channels: ['Web Chat', 'Mobile App', 'API'],
    services: ['ElevenLabs', 'Tavus'],
    knowledgeChunks: 8920,
    messagesTotal: 34700,
    lastActive: '12 min ago',
    createdAt: 'Mar 22, 2026',
    voice: 'Sarah (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-008',
    name: 'PureHome Decor Bot',
    slug: 'purehome-decor-bot',
    subCategory: 'D2C Home Decor',
    description: 'D2C home decor brand — helps customers discover products by room, style, and budget; handles cross-sell and cart recovery flows',
    status: 'active',
    avatar: 'PH',
    channels: ['WhatsApp', 'Web Chat'],
    services: ['ElevenLabs', 'Omnidimension'],
    knowledgeChunks: 8920,
    messagesTotal: 41200,
    lastActive: '5 min ago',
    createdAt: 'Dec 14, 2025',
    voice: 'Zara (ElevenLabs)',
    language: 'English, Arabic',
    whatsappNumber: '+971 50 123 4567',
  },
  {
    id: 'persona-009',
    name: 'BrewCraft Support Agent',
    slug: 'brewcraft-support-agent',
    subCategory: 'D2C Specialty Coffee',
    description: 'D2C specialty coffee brand — handles brewing guides, subscription management, and product FAQ for direct-to-consumer coffee orders',
    status: 'paused',
    avatar: 'BC',
    channels: ['API'],
    services: [],
    knowledgeChunks: 3400,
    messagesTotal: 9800,
    lastActive: '2 days ago',
    createdAt: 'Jan 28, 2026',
    voice: 'None',
    language: 'English',
  },
  {
    id: 'persona-010',
    name: 'ActiveWear Sales Bot',
    slug: 'activewear-sales-bot',
    subCategory: 'D2C Activewear',
    description: 'D2C activewear brand — delivers size guides, fabric comparisons, and sport-specific recommendations to drive purchase decisions',
    status: 'training',
    avatar: 'AW',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 4200,
    messagesTotal: 0,
    lastActive: 'Training...',
    createdAt: 'Apr 2, 2026',
    voice: 'Marcus (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-011',
    name: 'LuxeScent Fragrance Bot',
    slug: 'luxescent-fragrance-bot',
    subCategory: 'D2C Fragrance',
    description: 'D2C fragrance brand — guides customers through scent profiles, occasion-based recommendations, and gifting bundles',
    status: 'active',
    avatar: 'LS',
    channels: ['WhatsApp', 'API'],
    services: ['Omnidimension', 'Heygen'],
    knowledgeChunks: 5100,
    messagesTotal: 18900,
    lastActive: '45 min ago',
    createdAt: 'Feb 10, 2026',
    voice: 'Nova (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+1 (650) 555-0188',
  },
  {
    id: 'persona-012',
    name: 'GlobalShop Multilingual',
    slug: 'globalshop-multilingual',
    subCategory: 'D2C Global Commerce',
    description: 'D2C global storefront agent — multilingual product discovery and support for international D2C brands expanding across markets',
    status: 'active',
    avatar: 'GS',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs', 'Tavus'],
    knowledgeChunks: 2800,
    messagesTotal: 11400,
    lastActive: '30 min ago',
    createdAt: 'Mar 15, 2026',
    voice: 'Multilingual (ElevenLabs)',
    language: 'EN, ES, FR, DE, JA',
    whatsappNumber: '+1 (800) 555-0199',
  },
  {
    id: 'creator-c-001',
    name: 'Marcus Wealth',
    slug: 'marcus-wealth',
    subCategory: 'Personal Finance Advisor',
    description: 'Personal finance creator — answers questions on index investing, tax-loss harvesting, and building a $1M portfolio on a regular salary.',
    status: 'active',
    avatar: 'MW',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 8400,
    messagesTotal: 61400,
    lastActive: '5 min ago',
    createdAt: 'Jan 10, 2026',
    voice: 'Marcus (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-002',
    name: 'Priya Trades',
    slug: 'priya-trades',
    subCategory: 'Options Trading Coach',
    description: 'Finance creator — walks through covered calls, puts, and risk management in plain English for beginner options traders.',
    status: 'active',
    avatar: 'PT',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 5200,
    messagesTotal: 38900,
    lastActive: '12 min ago',
    createdAt: 'Feb 3, 2026',
    voice: 'Priya (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-003',
    name: 'Jordan Builds',
    slug: 'jordan-builds',
    subCategory: 'No-Code SaaS Builder',
    description: 'Course builder — guides students through validating, building, and launching no-code SaaS products with real revenue milestones.',
    status: 'active',
    avatar: 'JB',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 6100,
    messagesTotal: 47200,
    lastActive: '8 min ago',
    createdAt: 'Jan 22, 2026',
    voice: 'Jordan (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-004',
    name: 'Leila Learns',
    slug: 'leila-learns',
    subCategory: 'UX Design Mentor',
    description: 'Course builder — answers portfolio questions, critiques design work, and helps students land their first UX role.',
    status: 'active',
    avatar: 'LL',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 4300,
    messagesTotal: 29100,
    lastActive: '20 min ago',
    createdAt: 'Feb 14, 2026',
    voice: 'Leila (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-005',
    name: 'Coach Dani',
    slug: 'coach-dani',
    subCategory: 'Executive Leadership Coach',
    description: 'Executive coach — helps new managers navigate difficult conversations, set boundaries, and build leadership confidence.',
    status: 'active',
    avatar: 'CD',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 3800,
    messagesTotal: 22700,
    lastActive: '15 min ago',
    createdAt: 'Mar 5, 2026',
    voice: 'Dani (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-006',
    name: 'Ravi Mindset',
    slug: 'ravi-mindset',
    subCategory: 'Performance Coach',
    description: 'Performance coach — covers morning routines, deep work systems, and mental resilience for founders building under pressure.',
    status: 'active',
    avatar: 'RM',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 7200,
    messagesTotal: 55800,
    lastActive: '3 min ago',
    createdAt: 'Feb 28, 2026',
    voice: 'Ravi (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-007',
    name: 'Sasha Skin',
    slug: 'sasha-skin',
    subCategory: 'D2C Skincare Founder',
    description: 'D2C founder — recommends products from her clean skincare line, answers ingredient questions, and guides customers to their perfect routine.',
    status: 'active',
    avatar: 'SS',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 9100,
    messagesTotal: 73600,
    lastActive: '2 min ago',
    createdAt: 'Jan 18, 2026',
    voice: 'Sasha (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-008',
    name: 'Theo Gear',
    slug: 'theo-gear',
    subCategory: 'D2C Product Advisor',
    description: 'D2C founder — helps customers choose the right bag, accessories, and workspace setup from his minimalist everyday carry product line.',
    status: 'active',
    avatar: 'TG',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 4600,
    messagesTotal: 31500,
    lastActive: '25 min ago',
    createdAt: 'Mar 12, 2026',
    voice: 'Theo (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-009',
    name: 'Nina Crypto',
    slug: 'nina-crypto',
    subCategory: 'Web3 & DeFi Educator',
    description: 'Finance creator — demystifies DeFi and Web3 for skeptical beginners with clear, jargon-free explanations.',
    status: 'active',
    avatar: 'NC',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 5800,
    messagesTotal: 44200,
    lastActive: '10 min ago',
    createdAt: 'Feb 8, 2026',
    voice: 'Nina (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-010',
    name: 'Felix Fit',
    slug: 'felix-fit',
    subCategory: 'Fitness & Nutrition Coach',
    description: 'Course builder — delivers strength training programs and nutrition guidance for busy professionals with limited gym time.',
    status: 'active',
    avatar: 'FF',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 5500,
    messagesTotal: 36800,
    lastActive: '18 min ago',
    createdAt: 'Mar 20, 2026',
    voice: 'Felix (ElevenLabs)',
    language: 'English',
  },
];