export type PersonaStatus = 'active' | 'draft' | 'training' | 'paused' | 'archived';

export interface Persona {
  id: string;
  name: string;
  slug: string;
  description: string;
  status: PersonaStatus;
  avatar: string;
  channels: string[];
  services: string[];
  knowledgeChunks: number;
  messagesTotal: number;
  lastActive: string;
  createdAt: string;
  voice: string;
  language: string;
  whatsappNumber?: string;
}

export const personas: Persona[] = [
  {
    id: 'creator-c-001',
    name: 'Marcus Wealth',
    slug: 'marcus-wealth',
    description: 'Finance creator AI — answers questions on index investing, tax-loss harvesting, and building a $1M portfolio. Promotes courses and community membership.',
    status: 'active',
    avatar: 'MW',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 8400,
    messagesTotal: 61400,
    lastActive: '5 min ago',
    createdAt: 'Jan 10, 2026',
    voice: 'Marcus (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+1 (650) 555-0142',
  },
  {
    id: 'creator-c-002',
    name: 'Priya Trades',
    slug: 'priya-trades',
    description: 'Finance creator — walks through covered calls, puts, and risk management in plain English for beginner options traders.',
    status: 'active',
    avatar: 'PT',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 5200,
    messagesTotal: 38900,
    lastActive: '12 min ago',
    createdAt: 'Feb 3, 2026',
    voice: 'Priya (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-003',
    name: 'Jordan Builds',
    slug: 'jordan-builds',
    description: 'Course builder AI — guides students through validating, building, and launching no-code SaaS products. Handles course Q&A and upsells programs.',
    status: 'active',
    avatar: 'JB',
    channels: ['Web Chat', 'WhatsApp', 'API'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 7100,
    messagesTotal: 47200,
    lastActive: '8 min ago',
    createdAt: 'Feb 15, 2026',
    voice: 'Jordan (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+1 (415) 555-0101',
  },
  {
    id: 'creator-c-004',
    name: 'Leila Learns',
    slug: 'leila-learns',
    description: 'UX design course AI — answers portfolio questions, critiques design work, and helps students land their first UX role. Drives bootcamp enrollments.',
    status: 'active',
    avatar: 'LL',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 4800,
    messagesTotal: 29100,
    lastActive: '25 min ago',
    createdAt: 'Feb 20, 2026',
    voice: 'Leila (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-005',
    name: 'Coach Dani',
    slug: 'coach-dani',
    description: 'Executive coaching AI — helps new managers navigate difficult conversations, set boundaries, and build leadership confidence. Books 1:1 coaching sessions.',
    status: 'active',
    avatar: 'CD',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs', 'Tavus'],
    knowledgeChunks: 3900,
    messagesTotal: 22700,
    lastActive: '1 hr ago',
    createdAt: 'Mar 1, 2026',
    voice: 'Dani (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+1 (650) 555-0188',
  },
  {
    id: 'creator-c-006',
    name: 'Ravi Mindset',
    slug: 'ravi-mindset',
    description: 'High-performance coaching AI — covers morning routines, deep work systems, and mental resilience for founders. Promotes group coaching programs.',
    status: 'active',
    avatar: 'RM',
    channels: ['Web Chat', 'WhatsApp', 'API'],
    services: ['ElevenLabs'],
    knowledgeChunks: 6200,
    messagesTotal: 55800,
    lastActive: '3 min ago',
    createdAt: 'Mar 5, 2026',
    voice: 'Ravi (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+91 98765 43210',
  },
  {
    id: 'creator-c-007',
    name: 'Nina Crypto',
    slug: 'nina-crypto',
    description: 'DeFi & Web3 creator AI — breaks down wallets, staking, and on-chain risk without the hype. Drives newsletter subscriptions.',
    status: 'training',
    avatar: 'NC',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 3100,
    messagesTotal: 0,
    lastActive: 'Training...',
    createdAt: 'Apr 1, 2026',
    voice: 'Nina (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-008',
    name: 'Felix Fit',
    slug: 'felix-fit',
    description: 'Fitness course AI — answers workout questions, adjusts programs for injuries, and keeps students accountable. Drives program purchases.',
    status: 'training',
    avatar: 'FF',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 4200,
    messagesTotal: 0,
    lastActive: 'Training...',
    createdAt: 'Apr 2, 2026',
    voice: 'Felix (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-demo-001',
    name: 'Demo Concierge',
    slug: 'demo-concierge',
    description: 'Interactive product tour guide for PersonaMatrix — showcases platform features, workflows, and onboarding steps for new users.',
    status: 'active',
    avatar: 'DC',
    channels: ['Web Chat', 'API'],
    services: ['Heygen', 'Tavus'],
    knowledgeChunks: 1560,
    messagesTotal: 4300,
    lastActive: '3 hr ago',
    createdAt: 'Feb 20, 2026',
    voice: 'Adam (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-d2c-001',
    name: 'Sasha Skin (D2C Preview)',
    slug: 'sasha-skin',
    description: 'D2C commerce AI preview — recommends skincare products, answers ingredient questions, and guides customers to their perfect routine. (D2C vertical coming soon)',
    status: 'paused',
    avatar: 'SS',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 5800,
    messagesTotal: 73600,
    lastActive: 'Paused',
    createdAt: 'Mar 22, 2026',
    voice: 'Sasha (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-ott-001',
    name: 'StreamGuide (OTT Preview)',
    slug: 'streamguide-crime-drama',
    description: 'OTT viewer engagement preview — character Q&A, episode recaps, and personalized content discovery. (OTT vertical coming soon)',
    status: 'paused',
    avatar: 'SG',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 8920,
    messagesTotal: 34700,
    lastActive: 'Paused',
    createdAt: 'Mar 22, 2026',
    voice: 'Sarah (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-multilingual-001',
    name: 'Multilingual Welcome',
    slug: 'multilingual-welcome',
    description: 'First-touch multilingual greeter for global creator onboarding flows',
    status: 'active',
    avatar: 'ML',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs', 'Tavus'],
    knowledgeChunks: 2800,
    messagesTotal: 11400,
    lastActive: '30 min ago',
    createdAt: 'Mar 15, 2026',
    voice: 'Multilingual (ElevenLabs)',
    language: 'EN, ES, FR, DE, JA',
    whatsappNumber: '+1 (800) 555-0199',
  },
];