export type PersonaStatus = 'active' | 'draft' | 'training' | 'paused' | 'archived';

export interface Persona {
  id: string;
  name: string;
  slug: string;
  description: string;
  status: PersonaStatus;
  avatar: string;
  channels: string[];
  services: string[];
  knowledgeChunks: number;
  messagesTotal: number;
  lastActive: string;
  createdAt: string;
  voice: string;
  language: string;
  whatsappNumber?: string;
}

export const personas: Persona[] = [
  {
    id: 'persona-001',
    name: 'Aria Sales',
    slug: 'aria-sales',
    description: 'Outbound sales assistant for SaaS leads — qualifies prospects and books demos',
    status: 'active',
    avatar: 'AS',
    channels: ['WhatsApp', 'Web Chat', 'API'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 4820,
    messagesTotal: 28430,
    lastActive: '2 min ago',
    createdAt: 'Jan 12, 2026',
    voice: 'Aria (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+1 (415) 555-0101',
  },
  {
    id: 'persona-002',
    name: 'Support Bot v2',
    slug: 'support-bot-v2',
    description: 'Handles tier-1 support tickets, FAQ resolution, and escalation routing',
    status: 'active',
    avatar: 'SB',
    channels: ['Web Chat', 'API'],
    services: ['ElevenLabs'],
    knowledgeChunks: 12400,
    messagesTotal: 94100,
    lastActive: '8 min ago',
    createdAt: 'Nov 3, 2025',
    voice: 'Rachel (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-003',
    name: 'Maya HR',
    slug: 'maya-hr',
    description: 'Internal HR assistant for policy Q&A, onboarding, and leave management',
    status: 'active',
    avatar: 'MH',
    channels: ['WhatsApp'],
    services: ['Omnidimension'],
    knowledgeChunks: 3100,
    messagesTotal: 7820,
    lastActive: '1 hr ago',
    createdAt: 'Feb 5, 2026',
    voice: 'Maya (Omnidimension)',
    language: 'English, Hindi',
    whatsappNumber: '+91 98765 43210',
  },
  {
    id: 'persona-004',
    name: 'Kai Voice Agent',
    slug: 'kai-voice-agent',
    description: 'AI voice agent with natural language understanding for inbound and outbound calls',
    status: 'active',
    avatar: 'KV',
    channels: ['Voice AI', 'API'],
    services: ['ElevenLabs', 'Tavus'],
    knowledgeChunks: 2240,
    messagesTotal: 15600,
    lastActive: '22 min ago',
    createdAt: 'Mar 1, 2026',
    voice: 'Kai (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-005',
    name: 'Creator Persona — Alex',
    slug: 'creator-persona-alex',
    description: 'AI persona for creator Alex — engages fans 24/7, answers questions in creator voice, promotes courses and content',
    status: 'active',
    avatar: 'CA',
    channels: ['Web Chat', 'WhatsApp', 'API'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 6840,
    messagesTotal: 52300,
    lastActive: '5 min ago',
    createdAt: 'Mar 10, 2026',
    voice: 'Alex (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+1 (650) 555-0142',
  },
  {
    id: 'persona-006',
    name: 'OnRent Demo Concierge',
    slug: 'demo-concierge',
    description: 'Interactive product tour guide for OnRent — showcases rental management features, workflows, and onboarding steps for new users',
    status: 'active',
    avatar: 'DC',
    channels: ['Web Chat', 'API'],
    services: ['Heygen', 'Tavus'],
    knowledgeChunks: 1560,
    messagesTotal: 4300,
    lastActive: '3 hr ago',
    createdAt: 'Feb 20, 2026',
    voice: 'Adam (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-007',
    name: 'StreamGuide — Crime Drama',
    slug: 'streamguide-crime-drama',
    description: 'OTT viewer engagement persona for crime drama series — character Q&A, episode recaps, and personalized content discovery',
    status: 'active',
    avatar: 'SG',
    channels: ['Web Chat', 'Mobile App', 'API'],
    services: ['ElevenLabs', 'Tavus'],
    knowledgeChunks: 8920,
    messagesTotal: 34700,
    lastActive: '12 min ago',
    createdAt: 'Mar 22, 2026',
    voice: 'Sarah (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-008',
    name: 'Zara Retail',
    slug: 'zara-retail',
    description: 'E-commerce shopping assistant with product discovery and order tracking',
    status: 'active',
    avatar: 'ZR',
    channels: ['WhatsApp', 'Web Chat'],
    services: ['ElevenLabs', 'Omnidimension'],
    knowledgeChunks: 8920,
    messagesTotal: 41200,
    lastActive: '5 min ago',
    createdAt: 'Dec 14, 2025',
    voice: 'Zara (ElevenLabs)',
    language: 'English, Arabic',
    whatsappNumber: '+971 50 123 4567',
  },
  {
    id: 'persona-009',
    name: 'Ops Monitor',
    slug: 'ops-monitor',
    description: 'Infrastructure alert responder — interprets monitoring alerts and suggests fixes',
    status: 'paused',
    avatar: 'OM',
    channels: ['API'],
    services: [],
    knowledgeChunks: 6400,
    messagesTotal: 9800,
    lastActive: '2 days ago',
    createdAt: 'Jan 28, 2026',
    voice: 'None',
    language: 'English',
  },
  {
    id: 'persona-010',
    name: 'Fan Engagement — Sports',
    slug: 'fan-engagement-sports',
    description: 'Sports creator persona — delivers match insights, player stats, and fan Q&A in real time across web and WhatsApp',
    status: 'training',
    avatar: 'FE',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 4200,
    messagesTotal: 0,
    lastActive: 'Training...',
    createdAt: 'Apr 2, 2026',
    voice: 'Marcus (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'persona-011',
    name: 'Nova Customer Success',
    slug: 'nova-customer-success',
    description: 'Proactive success outreach — NPS follow-ups, renewal reminders, upsell conversations',
    status: 'active',
    avatar: 'NC',
    channels: ['WhatsApp', 'API'],
    services: ['Omnidimension', 'Heygen'],
    knowledgeChunks: 5100,
    messagesTotal: 18900,
    lastActive: '45 min ago',
    createdAt: 'Feb 10, 2026',
    voice: 'Nova (ElevenLabs)',
    language: 'English',
    whatsappNumber: '+1 (650) 555-0188',
  },
  {
    id: 'persona-012',
    name: 'Multilingual Welcome',
    slug: 'multilingual-welcome',
    description: 'First-touch multilingual greeter for global product onboarding flows',
    status: 'active',
    avatar: 'MW',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs', 'Tavus'],
    knowledgeChunks: 2800,
    messagesTotal: 11400,
    lastActive: '30 min ago',
    createdAt: 'Mar 15, 2026',
    voice: 'Multilingual (ElevenLabs)',
    language: 'EN, ES, FR, DE, JA',
    whatsappNumber: '+1 (800) 555-0199',
  },
  {
    id: 'creator-c-001',
    name: 'Marcus Wealth',
    slug: 'marcus-wealth',
    description: 'Personal finance creator — answers questions on index investing, tax-loss harvesting, and building a $1M portfolio on a regular salary.',
    status: 'active',
    avatar: 'MW',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 8400,
    messagesTotal: 61400,
    lastActive: '5 min ago',
    createdAt: 'Jan 10, 2026',
    voice: 'Marcus (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-002',
    name: 'Priya Trades',
    slug: 'priya-trades',
    description: 'Finance creator — walks through covered calls, puts, and risk management in plain English for beginner options traders.',
    status: 'active',
    avatar: 'PT',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 5200,
    messagesTotal: 38900,
    lastActive: '12 min ago',
    createdAt: 'Feb 3, 2026',
    voice: 'Priya (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-003',
    name: 'Jordan Builds',
    slug: 'jordan-builds',
    description: 'Course builder — guides students through validating, building, and launching no-code SaaS products with real revenue milestones.',
    status: 'active',
    avatar: 'JB',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 6100,
    messagesTotal: 47200,
    lastActive: '8 min ago',
    createdAt: 'Jan 22, 2026',
    voice: 'Jordan (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-004',
    name: 'Leila Learns',
    slug: 'leila-learns',
    description: 'Course builder — answers portfolio questions, critiques design work, and helps students land their first UX role.',
    status: 'active',
    avatar: 'LL',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 4300,
    messagesTotal: 29100,
    lastActive: '20 min ago',
    createdAt: 'Feb 14, 2026',
    voice: 'Leila (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-005',
    name: 'Coach Dani',
    slug: 'coach-dani',
    description: 'Executive coach — helps new managers navigate difficult conversations, set boundaries, and build leadership confidence.',
    status: 'active',
    avatar: 'CD',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 3800,
    messagesTotal: 22700,
    lastActive: '15 min ago',
    createdAt: 'Mar 5, 2026',
    voice: 'Dani (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-006',
    name: 'Ravi Mindset',
    slug: 'ravi-mindset',
    description: 'Performance coach — covers morning routines, deep work systems, and mental resilience for founders building under pressure.',
    status: 'active',
    avatar: 'RM',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 7200,
    messagesTotal: 55800,
    lastActive: '3 min ago',
    createdAt: 'Feb 28, 2026',
    voice: 'Ravi (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-007',
    name: 'Sasha Skin',
    slug: 'sasha-skin',
    description: 'D2C founder — recommends products from her clean skincare line, answers ingredient questions, and guides customers to their perfect routine.',
    status: 'active',
    avatar: 'SS',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs', 'Heygen'],
    knowledgeChunks: 9100,
    messagesTotal: 73600,
    lastActive: '2 min ago',
    createdAt: 'Jan 18, 2026',
    voice: 'Sasha (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-008',
    name: 'Theo Gear',
    slug: 'theo-gear',
    description: 'D2C founder — helps customers choose the right bag, accessories, and workspace setup from his minimalist everyday carry product line.',
    status: 'active',
    avatar: 'TG',
    channels: ['Web Chat'],
    services: ['ElevenLabs'],
    knowledgeChunks: 4600,
    messagesTotal: 31500,
    lastActive: '25 min ago',
    createdAt: 'Mar 12, 2026',
    voice: 'Theo (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-009',
    name: 'Nina Crypto',
    slug: 'nina-crypto',
    description: 'Finance creator — demystifies DeFi and Web3 for skeptical beginners with clear, jargon-free explanations.',
    status: 'active',
    avatar: 'NC',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 5800,
    messagesTotal: 44200,
    lastActive: '10 min ago',
    createdAt: 'Feb 8, 2026',
    voice: 'Nina (ElevenLabs)',
    language: 'English',
  },
  {
    id: 'creator-c-010',
    name: 'Felix Fit',
    slug: 'felix-fit',
    description: 'Course builder — delivers strength training programs and nutrition guidance for busy professionals with limited gym time.',
    status: 'active',
    avatar: 'FF',
    channels: ['Web Chat', 'WhatsApp'],
    services: ['ElevenLabs'],
    knowledgeChunks: 5500,
    messagesTotal: 36800,
    lastActive: '18 min ago',
    createdAt: 'Mar 20, 2026',
    voice: 'Felix (ElevenLabs)',
    language: 'English',
  },
];